// Theme colors based on brand guidelines
export const colors = {
  primary: '#2cb673',          // primary elements
  accent: '#b1e2c6',           // accents
  background: '#ebf8f1',       // background
  backgroundDarker: '#b1e2c6', // contrast
  backgroundLight: '#ebf8f1',  // sections
  text: '#1B5E20',             // text
  border: '#b1e2c6',           // borders
  footerBg: '#2cb673',         // footer background
  footerText: '#ebf8f1',       // footer
  hover: '#1e8f5a',            // hover state color
  white: 'white',
  black: 'black',
  grey: '#555',
  lightGrey: '#e0e0e0',
  error: '#e53935',            // error states and logout
  overlay: 'rgba(0,0,0,0.5)',
  warning: '#FFA500'
};

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { 
    flex: 1,
    backgroundColor: colors.background,
    minHeight: '100%',
    paddingHorizontal: 20, // Only horizontal padding
  },
    label: { 
      marginBottom: 10, 
      color: colors.text, 
      fontWeight: 'bold', 
      fontSize: 16,
      letterSpacing: 0.2,
    },
    autocompleteContainer: { 
      width: '100%', 
      maxWidth: 480,
      marginTop: 12,
      alignSelf: 'center',
    },
    input: {
      width: '100%',
      borderColor: colors.border,
      borderWidth: 1.5,
      borderRadius: 10,
      padding: 14,
      backgroundColor: colors.white,
      fontSize: 16,
      marginBottom: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.07,
      shadowRadius: 2,
      elevation: 1,
    },
    suggestions: {
      marginTop: 2,
      backgroundColor: '#fcfcfc',
      borderRadius: 8,
      maxHeight: 220,
      borderColor: '#ddd',
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    suggestion: {
      padding: 14,
      borderBottomColor: '#eee',
      borderBottomWidth: 1,
    },
    selected: { 
      marginTop: 18, 
      color: colors.text, 
      fontWeight: 'bold',
      fontSize: 16,
    },
    screenContainer: { 
      flex: 1, 
      backgroundColor: colors.background,
      paddingTop: 0,
    },
    contentContainer: {
      flex: 1,
      margin: '5%', // 5% inset from all edges
      padding: 16,
      backgroundColor: colors.backgroundLight,
      borderRadius: 12,
    },
    historyButton: {
    position: 'absolute',
    top: 32,
    right: 18,
    zIndex: 10,
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyButtonText: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.2,
  },
    addressHistory: {
      backgroundColor: colors.white,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
    addressHistoryText: {
      color: colors.primary,
      fontWeight: 'bold',
      fontSize: 16,
      letterSpacing: 0.2,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: colors.white,
      borderRadius: 12,
      padding: 24,
      width: 320,
      alignItems: 'stretch',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 6,
    },
    modalOption: {
      paddingVertical: 14,
      paddingHorizontal: 10,
      borderRadius: 6,
      marginBottom: 4,
      backgroundColor: colors.backgroundLight,
    },
    modalOptionText: {
      fontSize: 16,
      color: colors.text,
    },
    modalRecentHeader: {
      marginTop: 12,
      marginBottom: 4,
      fontWeight: 'bold',
      color: colors.grey,
      fontSize: 14,
    },
    modalClose: {
      marginTop: 16,
      alignSelf: 'flex-end',
    },
    modalCloseText: {
      color: colors.error,
      fontWeight: 'bold',
      fontSize: 16,
    },
    
    // New styles for header and sidebar button
    headerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      marginBottom: 22,
      paddingHorizontal: 2,
    },
  sidebarButton: {
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 32,
    left: 18,
    zIndex: 10,
  },
  returnButton: {
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 32,
    left: 18,
    zIndex: 10,
  },
    sidebarButtonText: {
      color: colors.primary,
      fontSize: 24,
    },
    
    // Sidebar styles
    overlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      zIndex: 1000,
    },
    sidebar: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '70%',
      height: '100%',
      backgroundColor: colors.white,
      paddingTop: 40,
      paddingHorizontal: 16,
      zIndex: 1001,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 5,
      bottom: 0,
    },
    sidebarHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sidebarTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
    },
    sidebarLinks: {
      flex: 1,
    },
    sidebarLink: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sidebarLinkText: {
      marginLeft: 10,
      fontSize: 16,
      color: colors.text,
    },
    sidebarLogoContainer: {
      width: '100%',
      alignItems: 'center',
      marginBottom: 28,
      marginTop: 10,
    },
    sidebarLogo: {
      width: 120,
      height: 80,
    },
    
    // Restaurant card styles
    restaurantCard: {
      padding: 18,
      borderRadius: 12,
      backgroundColor: colors.white,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 3,
      borderWidth: 1,
      borderColor: colors.border,
    },
    restaurantCardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    },
    restaurantLogoWrapper: {
      width: 56,
      height: 56,
      borderRadius: 12,
      backgroundColor: '#f7faf9',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    restaurantLogoImage: {
      width: 48,
      height: 48,
      borderRadius: 8,
    },
    restaurantName: {
      fontWeight: 'bold',
      fontSize: 18,
      color: colors.primary,
      marginBottom: 4,
    },
    restaurantAddress: {
      color: colors.grey,
      fontSize: 15,
    },
    authContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  authCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  authTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 18,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  authInput: {
    borderColor: colors.border,
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 14,
    backgroundColor: colors.backgroundLight,
    fontSize: 16,
    marginBottom: 16,
  },
  authButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  authButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  authLink: {
    color: colors.primary,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 6,
  },
  authRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  authLabel: {
    color: colors.text,
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 6,
    marginTop: 2,
    letterSpacing: 0.2,
  },
  passwordInputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  passwordInput: {
    paddingRight: 44, // space for the eye icon
    height: 48,       // set a fixed height for consistency
  },
  eyeButton: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
    zIndex: 2,
    height: 48, // match input height
  },
  profileChoiceRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
    gap: 16, // if not supported, use marginRight on button
  },
  profileChoiceRowTop: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 0,
    gap: 16,
  },
  profileWideButtonRow: {
    flexDirection: 'column',
    width: '100%',
    gap: 12,
    marginBottom: 32,
  },
  profileWideButtonGroup: {
    width: '100%',
    flexDirection: 'column',
    gap: 16,          // was 20
    marginBottom: 24, // was 36
    marginTop: 0,     // was 8
  },
  profileWideButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 18, // Slightly more vertical padding
    marginBottom: 0, // Use gap in group for spacing
    marginTop: 0,
    marginHorizontal: 0,
    width: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  profileChoiceButton: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    marginHorizontal: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  profileChoiceButtonAccent: {
    backgroundColor: colors.hover, // darker green accent
  },
  profileChoiceButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  profileTopControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 32,
    marginBottom: 8,
    paddingHorizontal: 24,
    gap: 18, // if not supported, use marginLeft on locationToggleRow
  },
  languageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
  },
  languageButtonText: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 6,
  },
  locationToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  locationToggleLabel: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 6,
    marginRight: 8,
  },
  faqSection: {
    marginTop: 28, // More space above FAQ
    marginBottom: 36,
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  faqTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 12,
  },
  faqItem: {
    marginBottom: 14,
  },
  faqQuestion: {
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 2,
  },
  faqAnswer: {
    color: colors.text,
    marginLeft: 4,
    marginBottom: 4,
  },
  welcomeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12, // was 24
    marginTop: 0,     // was 12
  },
  welcomeText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
  },
  userInfoText: {
    fontSize: 16,
    color: colors.text,
    marginBottom: 8,
  },

  // New styles for language and location toggle buttons
  languageOptionButton: {
    padding: 12,
    borderRadius: 8,
    marginVertical: 6,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
  },
  languageOptionButtonSelected: {
    backgroundColor: '#d0eaff',
  },
  locationToggleButton: {
    marginLeft: 12,
    padding: 4,
  },
  locationToggleButtonActive: {
    // Optional: highlight when active
  },
  searchHistoryHeader: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.primary,
    marginTop: 10,
    marginBottom: 6,
  },
  searchHistoryList: {
    maxHeight: 5 * 32, // ~5 entries, adjust if your row height is different
    marginBottom: 12,
  },
  basketBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 18,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 8,
    zIndex: 100,
  },
  basketBarCount: {
    fontWeight: 'bold',
    color: colors.primary,
    minWidth: 40,
    textAlign: 'left',
  },
  basketBarLabel: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    flex: 1,
  },
  basketBarValue: {
    fontWeight: 'bold',
    color: colors.primary,
    minWidth: 60,
    textAlign: 'right',
  },
  basketModalContent: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 24,
    marginTop: 'auto',
    marginBottom: 40,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  basketModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 12,
    textAlign: 'center',
  },
  basketModalItem: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingVertical: 10,
    marginBottom: 4,
  },
  basketModalItemName: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.text,
  },
  basketModalItemPrice: {
    color: colors.primary,
    fontWeight: 'bold',
    marginTop: 2,
  },
  basketModalNoteInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  basketModalNoteInput: {
    flex: 1,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    fontSize: 14,
    minHeight: 36,
    backgroundColor: colors.backgroundLight,
  },
  basketModalNoteSaveButton: {
    marginLeft: 8,
    backgroundColor: '#2cb673',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 32,
    minWidth: 44,
  },
  basketModalNoteSaveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  basketModalNotePreview: {
    fontSize: 13,
    color: colors.grey,
    marginTop: 4,
    fontStyle: 'italic',
  },
  basketModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
    gap: 10,
  },
  basketModalButton: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 2,
  },
  basketModalButtonSecondary: {
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  basketModalButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  basketModalButtonSecondaryText: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 16,
  },
  basketModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
  },
  checkoutScrollContainer: {
    paddingVertical: 28,
    paddingHorizontal: 0,
    backgroundColor: colors.background,
    minHeight: '100%',
  },
  checkoutTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 18,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  checkoutCard: {
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 18,
    marginHorizontal: 18,
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  checkoutEmptyText: {
    color: colors.grey,
    textAlign: 'center',
    fontSize: 16,
    paddingVertical: 12,
  },
  checkoutItemRow: {
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
    paddingBottom: 8,
  },
  checkoutItemName: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.text,
    flex: 1,
  },
  checkoutItemPrice: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  checkoutTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    alignItems: 'center',
  },
  checkoutTotalLabel: {
    fontWeight: 'bold',
    fontSize: 17,
    color: colors.text,
  },
  checkoutTotalValue: {
    fontWeight: 'bold',
    fontSize: 17,
    color: colors.primary,
  },
  checkoutInput: {
    borderColor: colors.border,
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 14,
    backgroundColor: colors.backgroundLight,
    fontSize: 16,
    marginTop: 8,
    marginBottom: 2,
  },
  checkoutPaymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 12,
  },
  checkoutPaymentButton: {
    flex: 1, // Ensures equal width for both buttons
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingVertical: 18,
    paddingHorizontal: 10,
    marginHorizontal: 0, // Remove margin to avoid shrinking
    borderWidth: 2,
    justifyContent: 'center',
    minHeight: 60,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },

  checkoutPaymentButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    elevation: 2,
    shadowOpacity: 0.12,
  },
  checkoutPaymentButtonText: {
    color: colors.text,
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 2,
  },
  checkoutPaymentButtonTextActive: {
    color: colors.white,
  },
  checkoutPaymentButtonLarge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 18,
    borderWidth: 2,
    borderColor: colors.border,
    justifyContent: 'center',
    minHeight: 60,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  checkoutPaymentButtonWide: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 18,
    borderWidth: 2,
    borderColor: colors.border,
    justifyContent: 'center',
    minHeight: 60,
    marginTop: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    // Make it span both columns
    width: '100%',
  },
  checkoutConfirmButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 18,
    marginHorizontal: 18,
    marginTop: 10,
    marginBottom: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  checkoutConfirmButtonText: {
    color: colors.white,
    fontSize: 19,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  checkoutCancelButton: {
    backgroundColor: colors.error, // Use error color for cancel
    borderRadius: 12,
    paddingVertical: 18,
    marginHorizontal: 18,
    marginTop: 10,
    marginBottom: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  checkoutCancelButtonText: {
    color: colors.white,
    fontSize: 19,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  basketRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  basketRowControls: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 2,
    gap: 6,
  },
  basketControlButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e0e0e0',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 2,
  },
  basketControlButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1B5E20',
  },
  basketQuantityText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 6,
    minWidth: 20,
    textAlign: 'center',
  },
  basketRemoveButton: {
    marginLeft: 8, // was 10, reduced for better fit
    backgroundColor: '#e53935',
    borderRadius: 16,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  basketRemoveButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  checkoutPaymentMobilePay: {
    backgroundColor: '#1976d2', // MobilePay blue
    borderColor: '#1976d2',
  },
  checkoutPaymentCreditCard: {
    backgroundColor: '#1565c0', // Credit card blue
    borderColor: '#1565c0',
  },
  checkoutPaymentBank: {
    backgroundColor: '#ffb300', // Bank transfer orange
    borderColor: '#ffb300',
  },
    paymentCheckmarkContainer: {
    position: 'absolute',
    top: -12,         // Move up, halfway outside the button
    right: -12,       // Move right, halfway outside the button
    zIndex: 2,
    backgroundColor: 'rgba(44,182,115,0.95)', // subtle green bg for contrast
    borderRadius: 16,
    padding: 2,
    borderWidth: 2,
    borderColor: '#fff', // white border for visibility
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 2,
  },
  menuProductTouchable: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.lightGrey,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12, // Add gap for spacing between image and text
  },
  menuProductImageWrapper: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: '#f7faf9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  menuProductImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
  },
  menuProductName: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  menuProductDescription: {
    color: colors.grey,
    marginTop: 2,
  },
  menuProductPrice: {
    color: colors.primary,
    marginTop: 4,
    fontWeight: 'bold',
  },
  menuProductCounter: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#ebf8f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  menuProductCounterText: {
    color: '#2cb673',
    fontWeight: 'bold',
    fontSize: 16,
  },
  checkoutAddressInput: {
    minHeight: 44,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.lightGrey,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: '#fafafa',
    marginTop: 8,
    marginBottom: 2,
  },
  checkoutAddressText: {
    color: '#222',
    fontSize: 16,
  },
  checkoutAddressPlaceholder: {
    color: '#888',
    fontSize: 16,
  },
  tipButtonRow: {
    flexDirection: 'row',
    marginBottom: 12,
    justifyContent: 'space-between',
    flexWrap: 'nowrap',
    gap: 0,
  },
  tipButton: {
    flex: 1,
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  tipButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    elevation: 2,
    shadowOpacity: 0.12,
  },
  tipButtonText: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 16,
  },
  tipButtonTextActive: {
    color: colors.white,
  },
  tipCustomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  tipCustomClose: {
    marginLeft: 8,
    padding: 4,
    backgroundColor: '#eafaf3',
    borderRadius: 16,
  },
  tipSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 12,
  },
  tipSummaryText: {
    fontWeight: 'bold',
    color: colors.primary,
    fontSize: 16,
  },
  tipRemoveButton: {
    marginLeft: 10,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  tipRemoveButtonText: {
    color: colors.primary,
    textDecorationLine: 'underline',
    fontWeight: 'bold',
    fontSize: 15,
  },
  orderDetailsWrapper: {
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.white,
    marginBottom: 18,
    padding: 0,
    overflow: 'hidden',
  },
  orderDetailsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#f7faf9',
  },
  orderDetailsSection: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  orderDetailsSectionTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: colors.text,
    marginBottom: 6,
  },
  orderSummaryBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 22,
    marginBottom: 18,
    marginTop: 10,
  },
  orderSummaryLabel: {
    fontWeight: 'bold',
    fontSize: 18,
    color: colors.text,
  },
  orderSummaryTotal: {
    fontWeight: 'bold',
    fontSize: 18,
    color: colors.primary,
  },
    editableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  editableInfoText: {
    color: '#2cb673',
    fontSize: 16,
    marginBottom: 8,
    fontWeight: 'bold',
  },
    checkoutSuggestions: {
    marginTop: 2,
    backgroundColor: '#fcfcfc',
    borderRadius: 8,
    maxHeight: 132, // 3 entries * 44px each (adjust as needed)
    borderColor: '#ddd',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  checkoutSuggestion: {
    padding: 14,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    backgroundColor: '#fcfcfc',
  },
  basketModalNoteIconButton: {
  marginLeft: 6,
  marginRight: 2,
  padding: 4,
  borderRadius: 16,
  justifyContent: 'center',
  alignItems: 'center',
  minWidth: 28,
  minHeight: 28,
},
  categoryButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    minHeight: 38,
    marginRight: 8,
    borderWidth: 1,
    borderColor: colors.accent,
    justifyContent: 'center',
  },
  categoryButtonActive: {
    backgroundColor: colors.primary,
    borderWidth: 0,
  },
  categoryButtonText: {
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 22,
    color: colors.text,
  },
  categoryButtonTextActive: {
    color: '#fff',
  },
  categoryDropdown: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    minHeight: 38,
    justifyContent: 'center',
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  categoryDropdownText: {
    fontWeight: 'bold',
    fontSize: 14,
    color: colors.text,
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownList: {
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 0,
    minWidth: 180,
    maxHeight: 260,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 22,
  },
  dropdownItemText: {
    fontSize: 15,
    color: colors.text,
  },
    deliveryTimeButton: {
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
    marginRight: 8,
    minWidth: 90,
    alignItems: 'center',
  },
  deliveryTimeButtonActive: {
    backgroundColor: colors.primary,
  },
  deliveryTimeButtonText: {
    color: colors.primary,
    fontWeight: 'bold',
  },
  deliveryDropdownButton: {
  flexDirection: 'row',
  alignItems: 'center',
  borderWidth: 1.5,
  borderColor: colors.primary,
  borderRadius: 10,
  paddingVertical: 12,
  paddingHorizontal: 16,
  backgroundColor: colors.white,
  marginTop: 8,
  marginBottom: 2,
  minWidth: 120,
  justifyContent: 'space-between',
},
deliveryDropdownButtonActive: {
  backgroundColor: colors.accent,
  borderColor: colors.primary,
},
deliveryDropdownButtonText: {
  color: colors.primary,
  fontWeight: 'bold',
  fontSize: 16,
},
deliveryDropdownList: {
  backgroundColor: colors.white,
  borderRadius: 10,
  borderWidth: 1,
  borderColor: colors.primary,
  marginTop: 4,
  marginBottom: 2,
  minWidth: 120,
  elevation: 4,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.10,
  shadowRadius: 6,
  zIndex: 20,
},
deliveryDropdownItem: {
  paddingVertical: 12,
  paddingHorizontal: 16,
},
deliveryDropdownItemActive: {
  backgroundColor: colors.primary,
},
deliveryDropdownItemText: {
  color: colors.text,
  fontSize: 16,
},
deliveryDropdownItemTextActive: {
  color: colors.white,
  fontWeight: 'bold',
},
deliveryDropdownOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  zIndex: 99,
  backgroundColor: 'transparent',
},
deliveryDropdownListAbsolute: {
  position: 'absolute',
  left: 0,
  right: 0,
  top: 60, // adjust if needed to match the dropdown button's position
  backgroundColor: colors.white,
  borderRadius: 10,
  borderWidth: 1,
  borderColor: colors.primary,
  minWidth: 120,
  elevation: 8,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 8,
  zIndex: 100,
},
deliveryTypeToggleWrapper: {
  flexDirection: 'row',
  position: 'relative',
  backgroundColor: '#eafaf3',
  borderRadius: 24,
  overflow: 'hidden',
  marginBottom: 6,
  height: 44,
  marginHorizontal: 0,
  // width: '100%', // REMOVE THIS
  // maxWidth: 420, // REMOVE THIS
  // alignSelf: 'stretch', // REMOVE THIS
},
deliveryTypeToggleOption: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 2,
  paddingVertical: 0,
  minWidth: 0, // Prevents growing wider than needed
},
deliveryTypeToggleOptionActive: {
  // No background, slider is behind
},
deliveryTypeToggleText: {
  color: '#1B5E20',
  fontWeight: 'bold',
  fontSize: 15,
  zIndex: 2,
},
deliveryTypeToggleTextActive: {
  color: '#fff',
},
deliveryTypeToggleSlider: {
  position: 'absolute',
  top: 0,
  left: 0,
  width: '50%',
  height: '100%',
  backgroundColor: '#2cb673',
  borderRadius: 24,
  zIndex: 1,
  // Remove transition properties for native
  // transitionProperty: 'left',
  // transitionDuration: '200ms',
},
ordersModalWrapper: {
  borderWidth: 1.5,
  borderColor: colors.border,
  borderRadius: 18,
  backgroundColor: colors.white,
  width: 300,
  maxWidth: '92%',
  padding: 0,
  overflow: 'hidden',
  elevation: 8,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.15,
  shadowRadius: 12,
  maxHeight: 420,
},
ordersModalPinnedHeader: {
  backgroundColor: '#f7faf9',
  borderTopLeftRadius: 18,
  borderTopRightRadius: 18,
  borderBottomWidth: 1,
  borderBottomColor: colors.border,
  paddingVertical: 14,
  paddingHorizontal: 18,
  alignItems: 'center',
  zIndex: 2,
},
ordersModalPinnedOrderNumber: {
  fontSize: 20,
  fontWeight: 'bold',
  color: colors.primary,
  letterSpacing: 0.5,
},
ordersModalTitle: {
  fontSize: 22,
  fontWeight: 'bold',
  color: colors.primary,
  padding: 18,
  borderBottomWidth: 1,
  borderBottomColor: colors.border,
  backgroundColor: '#f7faf9',
  textAlign: 'center',
},
ordersModalSection: {
  padding: 16,
  borderBottomWidth: 1,
  borderBottomColor: colors.border,
  backgroundColor: colors.white,
},
ordersModalSectionTitle: {
  fontWeight: 'bold',
  fontSize: 15,
  color: colors.text,
  marginBottom: 6,
},
ordersModalOverlay: {
  flex: 1,
  backgroundColor: colors.overlay,
  justifyContent: 'center',
  alignItems: 'center',
},
ordersModalClose: {
  marginTop: 10,
  alignSelf: 'center',
  backgroundColor: colors.primary,
  borderRadius: 8,
  paddingVertical: 10,
  paddingHorizontal: 32,
  marginBottom: 18,
},
ordersModalCloseText: {
  color: colors.white,
  fontWeight: 'bold',
  fontSize: 16,
  letterSpacing: 0.5,
},
});
